// <auto-generated />
using System;
using HttpApiServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HttpApiServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("HttpModels.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("HttpModels.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e3564cdc-b71c-4501-bf7c-654d21a7dbc9"),
                            Name = "Смарфоны"
                        },
                        new
                        {
                            Id = new Guid("fae008cc-7fc1-4c18-96b8-653fcd884bdf"),
                            Name = "USB накопители"
                        },
                        new
                        {
                            Id = new Guid("e63338e7-8916-4a81-bb70-3f147b781e8c"),
                            Name = "Ноутбуки"
                        },
                        new
                        {
                            Id = new Guid("5a4c651b-b83e-4fb5-ba5e-e6d9b80407a4"),
                            Name = "Наушники"
                        },
                        new
                        {
                            Id = new Guid("063ebf69-a031-4328-ac73-85a60b930f4f"),
                            Name = "Игровые консоли"
                        },
                        new
                        {
                            Id = new Guid("e5939c6a-048f-4a2b-a1cc-6856a8e578bf"),
                            Name = "Телевизоры"
                        });
                });

            modelBuilder.Entity("HttpModels.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UrlImage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("415ad2a3-2141-44da-b33d-3d4409126642"),
                            CategoryId = new Guid("e3564cdc-b71c-4501-bf7c-654d21a7dbc9"),
                            Name = "Смартфон Google Pixel 5a",
                            Price = 560m,
                            Quantity = 20,
                            UrlImage = "https://cdn1.ozone.ru/s3/multimedia-3/wc250/6237328203.jpg"
                        },
                        new
                        {
                            Id = new Guid("a9dc85e6-138d-45a3-9378-e74709d1290c"),
                            CategoryId = new Guid("fae008cc-7fc1-4c18-96b8-653fcd884bdf"),
                            Name = "USB накопитель Samsung",
                            Price = 30m,
                            Quantity = 35,
                            UrlImage = "https://cdn1.ozone.ru/multimedia/wc1200/1026248251.jpg"
                        },
                        new
                        {
                            Id = new Guid("2639c484-30e1-428e-840e-e745e3ad5b14"),
                            CategoryId = new Guid("e63338e7-8916-4a81-bb70-3f147b781e8c"),
                            Name = "Ноутбук Lenovo IdeaPad 4 15IX5P6",
                            Price = 830.50m,
                            Quantity = 15,
                            UrlImage = "https://cdn1.ozone.ru/s3/multimedia-7/wc1200/6166994971.jpg"
                        },
                        new
                        {
                            Id = new Guid("1c406f52-e4f1-4259-a768-9a548cad6d98"),
                            CategoryId = new Guid("5a4c651b-b83e-4fb5-ba5e-e6d9b80407a4"),
                            Name = "Наушники Sony WH-CH56030NW",
                            Price = 130.60m,
                            Quantity = 25,
                            UrlImage = "https://cdn1.ozone.ru/s3/multimedia-r/wc1200/6179635779.jpg"
                        },
                        new
                        {
                            Id = new Guid("a66bb5b5-8862-42b2-86bd-e3d0a41ea247"),
                            CategoryId = new Guid("063ebf69-a031-4328-ac73-85a60b930f4f"),
                            Name = "Microsoft Xbox Series X",
                            Price = 985m,
                            Quantity = 2,
                            UrlImage = "https://cdn1.ozone.ru/s3/multimedia-l/wc1200/6232471137.jpg"
                        },
                        new
                        {
                            Id = new Guid("92ae2eb4-de13-4da4-99f7-e6777e16e2c6"),
                            CategoryId = new Guid("e5939c6a-048f-4a2b-a1cc-6856a8e578bf"),
                            Name = "Телевизор Sony KD50X81J 50",
                            Price = 1000.89m,
                            Quantity = 15,
                            UrlImage = "https://cdn1.ozone.ru/s3/multimedia-n/wc1200/6068732087.jpg"
                        });
                });

            modelBuilder.Entity("HttpModels.Product", b =>
                {
                    b.HasOne("HttpModels.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HttpModels.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
